AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  4me Slack integration
Parameters:
  4MeDomainParameter:
    Type: String
    Default: 4me-demo.com
  BootstrapSecretApplicationParameter:
    Type: String
    Default: 4me-app-builder
  BootstrapSecretAccountParameter:
    Type: String
    Default: 4me-support
  OfferingReferenceParameter:
    Type: String
    Default: slack-integration

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    CodeUri: integration-lambda/
    Handler: app.lambdaHandler
    Runtime: nodejs14.x

Resources:
  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${OfferingReferenceParameter}"
      KmsMasterKeyId: "alias/aws/sqs"
  IntegrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      MemorySize: 128
      Environment:
        Variables:
          PARAM_4ME_DOMAIN: !Ref 4MeDomainParameter
          PARAM_OFFERING_REFERENCE: !Ref OfferingReferenceParameter
          PARAM_BOOTSTRAP_APP: !Ref BootstrapSecretApplicationParameter
          PARAM_BOOTSTRAP_ACCOUNT: !Ref BootstrapSecretAccountParameter
          SQS_QUEUE_URL: !Ref SqsQueue
      Events:
        Integration:
          Type: Api
          Properties:
            Path: /integration
            Method: ANY
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SqsQueue.Arn
            BatchSize: 1
      Policies:
      - Statement:
        - Sid: ReadSecrets
          Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BootstrapSecretApplicationParameter}/${4MeDomainParameter}/${BootstrapSecretAccountParameter}-*"
        - Sid: ReadSlackAppCredentials
          Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BootstrapSecretApplicationParameter}/${OfferingReferenceParameter}/${4MeDomainParameter}/slack_app_credentials-*"
        - Sid: ReadWriteInstanceSecrets
          Effect: Allow
          Action:
          - secretsmanager:CreateSecret
          - secretsmanager:GetSecretValue
          - secretsmanager:PutSecretValue
          Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BootstrapSecretApplicationParameter}/${OfferingReferenceParameter}/${4MeDomainParameter}/instances/*"
        - Sid: SendSQSMessages
          Effect: Allow
          Action:
          - sqs:SendMessage
          Resource: !GetAtt SqsQueue.Arn
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./integration-lambda
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IntegrationApi:
    Description: "API Gateway endpoint URL for Prod stage for Integration Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApi.Stage}/integration/"
  IntegrationFunction:
    Description: "Integration Lambda Function ARN"
    Value: !GetAtt IntegrationFunction.Arn
  IntegrationFunctionIamRole:
    Description: "Implicit IAM Role created for Integration Function"
    Value: !GetAtt IntegrationFunctionRole.Arn
  SqsQueueUrl:
    Description: "SQS queue URL"
    Value: !Ref SqsQueue
  SqsQueueArn:
    Description: "SQS queue ARN"
    Value: !GetAtt SqsQueue.Arn
