name: Run Tests

on:
  push:
    branches:
      - '**/*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Amsterdam"

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
